name: Mark a task complete

on:
  pull_request:
    types: [closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: panther-labs/github-asana-action@v3.0.4
        if: github.event.pull_request.merged
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          trigger-phrase-regex: '\/asana'
          action: 'add-comment'
          text: 'Closed due to PR merge'
      - uses: panther-labs/github-asana-action@v3.0.4
        if: github.event.pull_request.merged
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          trigger-phrase-regex: '\/asana'
          action: 'complete-task'
          is-complete: true